### ISSUE TITLE
What is the minimum memory requirements

### ISSUE THREAD

**Issue by ClaudeCoulombe** [termsuite/termsuite-core#109]
Bonjour,

What is the minimum memory requirements (RAM) for a server running Termsuite?

Merci

Claude Coulombe

**Comment by dcram** [comment]
Bonjour Claude,

You can reach a low memory requirement by reducing the value of parameter [`--capped-size`](http://termsuite.github.io/documentation/terminology-extractor-cli/#TerminologyExtractorCLI-capped-size). The default value is 500000. If you need to make it run with a maximum of 1Gb of heap space (JVM arg:  -Xmx 1g), you could try with 100000, or even less.

Also consider using [`--no-occurrence`](http://termsuite.github.io/documentation/terminology-extractor-cli/#TerminologyExtractorCLI-no-occurrence) to reduce the amount of memory used by TermSuite.

Damien

**Comment by ClaudeCoulombe** [comment]
Merci Damien!
