### ISSUE TITLE
Ajout lexiques transdisciplinaires / syntagmes définis (expressions figées)

### ISSUE THREAD

**Issue by dcram** [termsuite/termsuite-core#42]
TODO
1. Créer un nouveau type dans le type system de TermSuite : "Fixed Expression"
2. Créer une ressource UIMA pour la liste des expressions fixes,
3. Créer l'AE de reconnaissance des expressions fixes,
4. Décrémenter la fréquence des mots/termes qui se chevauchent, ou qui sont inclus (à voir), avec une expression fixe,
5. Écrire des tests JUnit.

**Comment by pompadour** [comment]
TODO
1. Créer un nouveau type dans le type system de TermSuite : "Fixed Expression"
2. Créer une ressource UIMA pour la liste des expressions fixes,
3. Créer l'AE de reconnaissance des expressions fixes,
4. Décrémenter la fréquence des mots/termes qui se chevauchent, ou qui sont inclus (à voir), avec une expression fixe,
5. Écrire des tests JUnit.

**Comment by dcram** [comment]
Implemented and merged into 2.2
