### ISSUE TITLE
TeiCollectionReader does not accept .tei files

### ISSUE THREAD

**Issue by neurovertex** [termsuite/termsuite-core#64]
As stated line 77 of termsuite-core/src/main/java/eu/project/ttc/readers/TeiCollectionReader.java, the FilenameFilter only accepts files with an extension of .xml, while the [documentation](http://termsuite.github.io/documentation/corpus/) clearly shows TEI files with a .tei extension.

**Comment by dcram** [comment]
You are right, Thank you ! Would you suggest there is no file extension constraint on TeiCollectionReader ? Or maybe a *.(tei|xml) ? Or set the constraint to *.tei to match the documentation ?

**Comment by neurovertex** [comment]
I'd suggest to accept both .tei and .xml, as naming TEI files .xml makes sense. Maybe, when no files are matched, output a warning such as "No file found with extension {extension} in input directory."

**Comment by dcram** [comment]
Another comment, TEI support is currently broken in TermSuite (see issue #24) since I can't find any event-based xml parser (SAX does not fit) that gives the right begin/end offsets.

**Comment by neurovertex** [comment]
Fair enough, I'll stick to TXT for now then I suppose
