### ISSUE TITLE
No such resource: ScriptTermIndex_1479999264822

### ISSUE THREAD

**Issue by ghost** [termsuite/termsuite-core#89]
Bonjour,

voici la commande que je lance:

$ java -Xms1g -Xmx2g -cp termsuite-core-2.3.1.jar eu.project.ttc.tools.cli.TermSuiteTerminoCLI -t /home/kroham/tools/TreeTagger -l en -r /home/kroham/tools/termsuite-core-2.3.1/termsuite-resources.jar --text "Wind energy is the energy of tomorrow."

j'ai une erreur: 
16:12:46.036 [main] INFO eu.project.ttc.tools.cli.TermSuiteTerminoCLI - Logging to /home/kroham/tools/termsuite-core-2.3.1/logs/termsuite-20161124-161246.log
16:12:46.059 [main] INFO eu.project.ttc.tools.cli.TermSuiteCLIUtils - with option: -r (--resource-pack) /home/kroham/tools/termsuite-core-2.3.1/termsuite-resources.jar
16:12:46.060 [main] INFO eu.project.ttc.tools.cli.TermSuiteCLIUtils - with option: -t (--tagger-home) /home/kroham/tools/TreeTagger
16:12:46.060 [main] INFO eu.project.ttc.tools.cli.TermSuiteCLIUtils - with option: -l (--language) en
16:12:46.060 [main] INFO eu.project.ttc.tools.cli.TermSuiteCLIUtils - with option: --text Wind energy is the energy of tomorrow.
16:12:46.338 [main] INFO eu.project.ttc.tools.TermSuitePipeline - Resource URL prefix is: jar:file:/home/kroham/tools/termsuite-core-2.3.1/termsuite-resources.jar!/
16:12:47.004 [main] INFO eu.project.ttc.tools.cli.TermSuiteTerminoCLI - Running TermSuite pipeline (inline mode)
16:12:51.001 [main] INFO eu.project.ttc.engines.TermIndexBlacklistWordFilterAE - Starting word filtering
16:12:51.001 [main] INFO eu.project.ttc.engines.TermSpecificityComputer - Computing specificities and measures
16:12:51.002 [main] INFO eu.project.ttc.engines.morpho.CompostAE - Starting morphology analysis
16:12:51.079 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Start syntactic term gathering
16:12:51.097 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Biggest class is null, size: 0
16:12:51.098 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Number of term pairs to test: 0
16:12:51.103 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Biggest class is null, size: 0
16:12:51.103 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Number of term pairs to test: 0
16:12:51.106 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Biggest class is null, size: 0
16:12:51.106 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Number of term pairs to test: 0
16:12:51.107 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Biggest class is null, size: 0
16:12:51.107 [main] INFO eu.project.ttc.engines.SyntacticTermGatherer - Number of term pairs to test: 0
16:12:51.121 [main] INFO eu.project.ttc.engines.GraphicalVariantGatherer - Start graphical term gathering
16:12:51.123 [main] INFO eu.project.ttc.engines.ExtensionDetecter - Starting extension detection
16:12:51.123 [main] INFO eu.project.ttc.engines.ScorerAE - Starting Scorying terms
16:12:51.125 [main] INFO eu.project.ttc.termino.engines.TermVariationScorer - Scorying term index f16d05c7-918c-44d5-be67-d197c4ebc2d6
16:12:51.133 [main] INFO eu.project.ttc.termino.engines.TermVariationScorer - Filtered 0 terms out of 5
16:12:51.133 [main] INFO eu.project.ttc.termino.engines.TermVariationScorer - Filtered 0 variants out of 0
16:12:51.133 [main] INFO eu.project.ttc.engines.Ranker - Starting Ranking terms
16:12:51.135 [main] INFO eu.project.ttc.engines.cleaner.AbstractTermIndexCleaner - Cleaning TermIndex f16d05c7-918c-44d5-be67-d197c4ebc2d6 on property WR_LOG
16:12:51.150 [main] INFO eu.project.ttc.engines.CasStatCounter - [at end of pipeline] WordAnnotation: 7 
16:12:51.151 [main] INFO eu.project.ttc.engines.CasStatCounter - [at end of pipeline] Nb terms:    5 [sw: 3, mw: 2]
16:12:51.152 [main] INFO eu.project.ttc.engines.CasStatCounter - [at end of pipeline] Nb words:    4 [compounds: 0]
16:12:51.152 [main] INFO eu.project.ttc.engines.CasStatCounter - [at end of pipeline] Nb occurrences: 6 [primary: 0]
16:12:51.153 [main] INFO eu.project.ttc.engines.CasStatCounter - [at end of pipeline] Nb variants: 0 [morph: 0, syn: 0, graph: 0]
Term index: 
Exception in thread "main" java.lang.IllegalArgumentException: No such resource: ScriptTermIndex_1479999264822
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
	at eu.project.ttc.tools.TermSuiteResourceManager.get(TermSuiteResourceManager.java:59)
	at eu.project.ttc.tools.cli.TermSuiteTerminoCLI.run(TermSuiteTerminoCLI.java:481)
	at eu.project.ttc.tools.cli.TermSuiteTerminoCLI.main(TermSuiteTerminoCLI.java:303)

$ file /home/kroham/tools/termsuite-core-2.3.1/termsuite-resources.jar
/home/kroham/tools/termsuite-core-2.3.1/termsuite-resources.jar: Java archive data (JAR)

je suis sur Ubuntu 16.04.1, openjdk version "1.8.0_111"

Merci d'avance, cdt.

**Comment by dcram** [comment]
Il s'agit probablement d'un bug avec l'option `--text`. Merci de l'avoir signalé.

Vous pouvez le contourner en plaçant votre texte dans un fichier `./corpus/file.txt`, puis : 

```
java -Xms1g -Xmx2g -cp termsuite-core-2.3.1.jar eu.project.ttc.tools.cli.TermSuiteTerminoCLI -t /home/kroham/tools/TreeTagger -l en -r /home/kroham/tools/termsuite-core-2.3.1/termsuite-resources.jar -c ./corpus/
```

**Comment by dcram** [comment]
I tried to fix the issue but another one has raised with the inline `--text` feature. The command line option parser I use (class Options in [Commons CLI 1.3](https://commons.apache.org/proper/commons-cli/apidocs/org/apache/commons/cli/Options.html) lib) does not parse well long strings between quotes in command lines. It's strange, it worked perfectly fine long time ago when I implemented this option.

It is better for me not to fix it now anyway. The `--text` option was just a debugging tool from command line, but you can still extract the terminology without any problem from a regular file as described above.

Thank you again for reporting.
